/*
  # Fix Team Member Management RLS Policies

  1. Problem
    - The current INSERT policy only allows super_admins or users creating their own profile
    - This prevents admins from adding new team members
    - The `id` field was being manually set which conflicts with the `auth.uid() = id` check

  2. Solution
    - Allow admins (and above) to INSERT new profiles
    - Allow admins (and above) to UPDATE any profile
    - Remove the direct insert capability from anon (unnecessary)
    - Ensure the id is generated by default using gen_random_uuid()

  3. Changes
    - Add INSERT policy for admins to create team members
    - Add UPDATE policy for admins to modify team members
    - Keep existing policies for users to manage their own profiles
    - Keep super_admin policies for full access
*/

-- Drop existing policies that are too restrictive
DROP POLICY IF EXISTS "Super admins can insert profiles" ON profiles;
DROP POLICY IF EXISTS "Super admins can update any profile" ON profiles;

-- Create new INSERT policy: Admins can insert new team members
CREATE POLICY "Admins can insert team members"
  ON profiles
  FOR INSERT
  TO authenticated
  WITH CHECK (
    is_admin_or_above()
  );

-- Create new UPDATE policy: Admins can update any profile
CREATE POLICY "Admins can update any profile"
  ON profiles
  FOR UPDATE
  TO authenticated
  USING (is_admin_or_above())
  WITH CHECK (is_admin_or_above());

-- Add DELETE policy for admins
CREATE POLICY "Admins can delete team members"
  ON profiles
  FOR DELETE
  TO authenticated
  USING (is_admin_or_above());

-- Ensure the id column has a default UUID
DO $$
BEGIN
  -- Check if id column default is not set
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'profiles'
    AND column_name = 'id'
    AND column_default IS NOT NULL
  ) THEN
    ALTER TABLE profiles ALTER COLUMN id SET DEFAULT gen_random_uuid();
  END IF;
END $$;